version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    restart: unless-stopped
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1907
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1907
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1907
      - POSTGRES_DB=bank_test
    ports:
      - "5432:5432"
volumes:
  pgdata:
